spring.application.name=Online-Food-Ordering


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/zosh_food1
#spring.datasource.username=postgres
#spring.datasource.password=Manish1234@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

frontend.url = ${FRONTEND_URL}

spring.jpa.show-sql: true